FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    nano \
    git \
    tree \
    && apt-get clean

WORKDIR /app

COPY commands.sh /app/commands.sh

RUN chmod +x /app/commands.sh

CMD ["bash", "/app/commands.sh"]